language: java
sudo: false
install: mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean verify -Dgpg.skip=true
after_success:
  - mvn -Dgpg.skip=true cobertura:cobertura coveralls:report
jdk:
  - oraclejdk8
  - openjdk7